### ISSUE TITLE
Question about dataset preparation

### ISSUE THREAD

**Issue by hlinhn** [zhangy76/PhysMoP#2]
Thank you for your work! 

I have a question about AMASS data preparation. In `AMASS.py` you deleted joint 9, 10, why is this done? When I checked AMASS data format it should correspond to `spine3` and `left_foot`, is that correct or have I missed something?

https://github.com/zhangy76/PhysMoP/blob/85c235e4c2562e7d2efda4ff0dda94c7283f885e/AMASS.py#L82

Another side question is how are the rest of the datasets processed (H3.6M, 3DPW)? Is it also smoothed out the same way AMASS is?
Thank you for your help!

**Comment by zhangy76** [comment]
Close due to inactivity. Feel free to reopen.

**Comment by zhangy76** [comment]
the detailed guidance is not available, sorry for the dirty code. But you may check the data preprocessing code 

https://github.com/zhangy76/PhysMoP/blob/85c235e4c2562e7d2efda4ff0dda94c7283f885e/AMASS.py#L66

to find the changes to the original SMPL joint angles
