### ISSUE TITLE
Human3.6M

### ISSUE THREAD

**Issue by Deante-dx** [zhangy76/PhysMoP#3]
Thank you for your kind words. Regarding the code for Human3.6M, can you provide it to me?

**Comment by zhangy76** [comment]
Hi, thanks for your interest. I may not be able to provide the code soon, but the code for Human3.6M should be very similar to what we have here. Basically, we need to
   - download the motion data from https://github.com/mks0601/NeuralAnnot_RELEASE 
   - follow https://github.com/zhangy76/PhysMoP/blob/main/AMASS.py to preprocess the data
   - change dataset to H36M in https://github.com/zhangy76/PhysMoP/blob/85c235e4c2562e7d2efda4ff0dda94c7283f885e/dataset/mixed_dataset.py#L8C37-L8C57 and https://github.com/zhangy76/PhysMoP/blob/85c235e4c2562e7d2efda4ff0dda94c7283f885e/dataset/mixed_dataset.py#L8C37-L8C57

Please let know if there is any further issue.

Yufei

**Comment by zhangy76** [comment]
Close due to being inactive, please feel free to reopen.
