### ISSUE TITLE
The processing code of Human3.6M and 3DPW

### ISSUE THREAD

**Issue by HitBadTrap** [zhangy76/PhysMoP#5]
Great Work! However, I'm confused about which file I should download for Human3.6M from https://github.com/mks0601/NeuralAnnot_RELEASE. There are three links (data, SMPL parameters, and SMPL-X parameters).  

Another issue is when will you share the processing code of Human3.6M and 3DPW? It's essential to me.

Thanks a lot.

**Comment by zhangy76** [comment]
Hi, thanks, for Human3.6M data, please download https://1drv.ms/f/s!All7gdNh7XE5oRb-ZscrxlS75Ogb?e=EaFfQz.

For the preprocessing code of Human3.6M and 3DPW, as long as the data files are downloaded, you will find they share very similar format, you can directly use the same preprocessing code but only need change the folder path.

**Comment by HitBadTrap** [comment]
I notice that the data of H36m does not contain gender_id and framerate, what should I set them to?

**Comment by KD-NU** [comment]
Dear author, is the origin framerate of H36m data 60 fps?

**Comment by zhangy76** [comment]
Close as being inactive. Please feel free to open again, thanks.

**Comment by satwiksunnam19** [comment]
Hey @zhangy76 , i think so the data for testing which you've provided above link seems not working, it's kind of authenticating in loop, can you please look into this
